export const books = [
  {
    name: "The Shadow of the Wind",
    authorName: "Carlos Ruiz Zafón",
    genre: "Mystery",
    language: "English",
    Description: "A young boy discovers a mysterious book that leads him into a labyrinth of secrets and danger.",
    numberOfPages: 487,
    pageAt: 0,
  },
  {
    name: "1984",
    authorName: "George Orwell",
    genre: "Dystopian",
    language: "English",
    Description: "A chilling portrayal of a totalitarian society where individuality is forbidden.",
    numberOfPages: 328,
    pageAt: 0,
  },
  {
    name: "Pride and Prejudice",
    authorName: "Jane Austen",
    genre: "Romance",
    language: "English",
    Description: "A classic tale of love, misunderstandings, and societal expectations.",
    numberOfPages: 279,
    pageAt: 0,
  },
  {
    name: "The Great Gatsby",
    authorName: "F. Scott Fitzgerald",
    genre: "Classic",
    language: "English",
    Description: "A story of wealth, love, and tragedy in the Jazz Age.",
    numberOfPages: 180,
    pageAt: 0,
  },
  {
    name: "To Kill a Mockingbird",
    authorName: "Harper Lee",
    genre: "Fiction",
    language: "English",
    Description: "A powerful exploration of racial injustice and moral growth in the American South.",
    numberOfPages: 281,
    pageAt: 0,
  },
  {
    name: "The Alchemist",
    authorName: "Paulo Coelho",
    genre: "Philosophical Fiction",
    language: "English",
    Description: "A shepherd boy embarks on a journey to discover his personal legend.",
    numberOfPages: 208,
    pageAt: 0,
  },
  {
    name: "The Catcher in the Rye",
    authorName: "J.D. Salinger",
    genre: "Literary Fiction",
    language: "English",
    Description: "A young man's journey through New York City as he grapples with alienation and identity.",
    numberOfPages: 234,
    pageAt: 0,
  },
  {
    name: "Harry Potter and the Sorcerer's Stone",
    authorName: "J.K. Rowling",
    genre: "Fantasy",
    language: "English",
    Description: "A young boy discovers he is a wizard and begins his journey at Hogwarts School of Witchcraft and Wizardry.",
    numberOfPages: 309,
    pageAt: 0,
  },
  {
    name: "The Hobbit",
    authorName: "J.R.R. Tolkien",
    genre: "Fantasy",
    language: "English",
    Description: "A hobbit embarks on an epic adventure to reclaim a treasure guarded by a dragon.",
    numberOfPages: 310,
    pageAt: 0,
  },
  {
    name: "The Lord of the Rings",
    authorName: "J.R.R. Tolkien",
    genre: "Fantasy",
    language: "English",
    Description: "A fellowship is formed to destroy a powerful ring and save Middle-earth from darkness.",
    numberOfPages: 1178,
    pageAt: 0,
  },
  {
    name: "The Da Vinci Code",
    authorName: "Dan Brown",
    genre: "Thriller",
    language: "English",
    Description: "A symbologist and a cryptologist unravel a mystery tied to a secret society.",
    numberOfPages: 489,
    pageAt: 0,
  },
  {
    name: "The Hunger Games",
    authorName: "Suzanne Collins",
    genre: "Dystopian",
    language: "English",
    Description: "A young girl fights for survival in a brutal televised competition.",
    numberOfPages: 374,
    pageAt: 0,
  },
  {
    name: "The Book Thief",
    authorName: "Markus Zusak",
    genre: "Historical Fiction",
    language: "English",
    Description: "A young girl in Nazi Germany finds solace in stealing books and sharing them with others.",
    numberOfPages: 552,
    pageAt: 0,
  },
  {
    name: "The Night Circus",
    authorName: "Erin Morgenstern",
    genre: "Fantasy",
    language: "English",
    Description: "A magical competition unfolds within a mysterious circus that appears without warning.",
    numberOfPages: 387,
    pageAt: 0,
  },
  {
    name: "The Martian",
    authorName: "Andy Weir",
    genre: "Science Fiction",
    language: "English",
    Description: "An astronaut stranded on Mars must use his ingenuity to survive and signal Earth for rescue.",
    numberOfPages: 369,
    pageAt: 0,
  },
];