import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MobNavbar from "./_components/MobNavbar";
import MobSideBar from "./_components/MobSideBar";
import Navbar from "./_components/NavBar";
import TabSidebar from "./_components/TabSideBar";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        antialiased bg-[#E5F6EE] relative 
        flex flex-col sm:flex-row`}
      >
        <Navbar/>
        <TabSidebar />
        <MobNavbar/>
        <MobSideBar/>
        {children}
      </body>
    </html>
  );
}
